/*
Copyright 2016 Jun Wako <wakojun@gmail.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#include "unimap_trans.h"


#define AC_FN0 ACTION_LAYER_MOMENTARY(1)
/*
#ifdef KEYMAP_SECTION_ENABLE
const action_t actionmaps[][UNIMAP_ROWS][UNIMAP_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
#else
const action_t actionmaps[][UNIMAP_ROWS][UNIMAP_COLS] PROGMEM = {
#endif
    UNIMAP(
              F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24,
    ESC,      F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10, F11, F12,           PSCR,SLCK,PAUS,         VOLD,VOLU,MUTE,
    GRV, 1,   2,   3,   4,   5,   6,   7,   8,   9,   0,   MINS,EQL, JYEN,BSPC,     INS, HOME,PGUP,    NLCK,PSLS,PAST,PMNS,
    TAB, Q,   W,   E,   R,   T,   Y,   U,   I,   O,   P,   LBRC,RBRC,     BSLS,     DEL, END, PGDN,    P7,  P8,  P9,  PPLS,
    CAPS,A,   S,   D,   F,   G,   H,   J,   K,   L,   SCLN,QUOT,     NUHS,ENT,                         P4,  P5,  P6,  PCMM,
    LSFT,NUBS,Z,   X,   C,   V,   B,   N,   M,   COMM,DOT, SLSH,     RO,  RSFT,          UP,           P1,  P2,  P3,  PENT,
    LCTL,LGUI,LALT,MHEN,          SPC,           HENK,KANA,RALT,RGUI,APP, FN0,      LEFT,DOWN,RGHT,    P0,       PDOT,PEQL
    ),
    UNIMAP(
              TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,
    GRV,      F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24,           TRNS,TRNS,TRNS,         TRNS,TRNS,TRNS,
    ESC, F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10, F11, F12, INS, DEL,      TRNS,TRNS,TRNS,    TRNS,TRNS,TRNS,TRNS,
    CAPS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,PSCR,SLCK,PAUS,UP,  INS,      TRNS,     TRNS,TRNS,TRNS,    TRNS,TRNS,TRNS,TRNS,
    TRNS,VOLD,VOLU,MUTE,TRNS,TRNS,TRNS,TRNS,HOME,PGUP,LEFT,RGHT,     TRNS,TRNS,                        TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,END, PGDN,DOWN,     TRNS,TRNS,          PGUP,         TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,          TRNS,          TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     HOME,PGDN,END,     TRNS,     TRNS,TRNS
    ),
}; */

/*
const action_t actionmaps[][UNIMAP_ROWS][UNIMAP_COLS] PROGMEM = {
    UNIMAP(
              F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24,
    ESC,      F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10, F11, F12,           PSCR,SLCK,PAUS,         VOLD,VOLU,MUTE,
    GRV, 1,   2,   3,   4,   5,   6,   7,   8,   9,   0,   MINS,EQL, JYEN,BSPC,     INS, HOME,PGUP,    NLCK,PSLS,PAST,PMNS,
    TAB, Q,   W,   E,   R,   T,   Y,   U,   I,   O,   P,   LBRC,RBRC,     BSLS,     DEL, END, PGDN,    P7,  P8,  P9,  PPLS,
    CAPS,A,   S,   D,   F,   G,   H,   J,   K,   L,   SCLN,QUOT,     NUHS,ENT,                         P4,  P5,  P6,  PCMM,
    LSFT,NUBS,Z,   X,   C,   V,   B,   N,   M,   COMM,DOT, SLSH,     RO,  RSFT,          UP,           P1,  P2,  P3,  PENT,
    LCTL,LGUI,LALT,MHEN,          SPC,           HENK,KANA,RALT,RGUI,FN0, RCTL,     LEFT,DOWN,RGHT,         P0,  PDOT,PEQL
    ),
    UNIMAP(
              TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,
    GRV,      TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,          TRNS,TRNS,TRNS,         TRNS,TRNS,TRNS,
    ESC, F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9,  F10, F11, F12, INS, DEL,      TRNS,TRNS,TRNS,    TRNS,TRNS,TRNS,TRNS,
    CAPS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,PSCR,SLCK,PAUS,UP,  INS,      TRNS,     TRNS,TRNS,TRNS,    TRNS,TRNS,TRNS,TRNS,
    TRNS,VOLD,VOLU,MUTE,TRNS,TRNS,TRNS,TRNS,HOME,PGUP,LEFT,RGHT,     TRNS,TRNS,                        TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,END, PGDN,DOWN,     TRNS,TRNS,          PGUP,         TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,          TRNS,          TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     HOME,PGDN,END,          TRNS,TRNS,TRNS
    ),
};*/


const uint8_t PROGMEM unimap_trans_dest_cs1_5251[MATRIX_ROWS_DEST][MATRIX_COLS_DEST] = {

  { UNIMAP_NO,  UNIMAP_Z,    UNIMAP_X,    UNIMAP_C,    UNIMAP_V,  UNIMAP_B,    UNIMAP_N,    UNIMAP_M   }, // 00-07
  { UNIMAP_COMMA,  UNIMAP_DOT,    UNIMAP_SLASH,    UNIMAP_KP_SLASH,    UNIMAP_KP_ASTERISK,  UNIMAP_NO,    UNIMAP_BSLASH,    UNIMAP_SPACE   }, // 08-0F
  { UNIMAP_NO,  UNIMAP_A,    UNIMAP_S,    UNIMAP_D,    UNIMAP_F,  UNIMAP_G,    UNIMAP_H,    UNIMAP_J   }, // 10-17
  { UNIMAP_K,  UNIMAP_L,    UNIMAP_SCOLON,    UNIMAP_QUOTE,    UNIMAP_NONUS_HASH,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 18-1F
  { UNIMAP_TAB,  UNIMAP_Q,    UNIMAP_W,    UNIMAP_E,    UNIMAP_R,  UNIMAP_T,    UNIMAP_Y,    UNIMAP_U   }, // 20-27
  { UNIMAP_I,  UNIMAP_O,    UNIMAP_P,    UNIMAP_LBRACKET,    UNIMAP_RBRACKET,  UNIMAP_ENTER,    UNIMAP_NO,    UNIMAP_NO   }, // 28-2F
  { UNIMAP_NO,  UNIMAP_1,    UNIMAP_2,    UNIMAP_3,    UNIMAP_4,  UNIMAP_5,    UNIMAP_6,    UNIMAP_7   }, // 30-37
  { UNIMAP_8,  UNIMAP_9,    UNIMAP_0,    UNIMAP_MINS,    UNIMAP_EQL,  UNIMAP_BSPC,    UNIMAP_ESCAPE,    UNIMAP_NO   }, // 38-3F
  { UNIMAP_KP_0,  UNIMAP_KP_1,    UNIMAP_KP_2,    UNIMAP_KP_3,    UNIMAP_KP_4,  UNIMAP_KP_5,    UNIMAP_KP_6,    UNIMAP_KP_7   }, // 40-47
  { UNIMAP_KP_8,  UNIMAP_KP_9,    UNIMAP_KP_DOT,    UNIMAP_NLCK,    UNIMAP_SCROLLLOCK,  UNIMAP_KP_PLUS,    UNIMAP_KP_MINUS,    UNIMAP_NO   }, // 48-4F
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_CAPSLOCK,  UNIMAP_NO,    UNIMAP_RSHIFT,    UNIMAP_LSHIFT   }, // 50-57
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 58-5F
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 60-67
  { UNIMAP_RCTRL,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_F3,  UNIMAP_F4,    UNIMAP_F5,    UNIMAP_F2   }, // 68-6F
  { UNIMAP_F8,  UNIMAP_F7,    UNIMAP_F9,    UNIMAP_F10,    UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 70-77
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_F1,  UNIMAP_F6,    UNIMAP_LCTRL,    UNIMAP_NO   }, // 78-7F
  //   0             1             2             3             4           5            6             7
  //   8             9             A             B             C           D            E             F
};


const uint8_t PROGMEM unimap_trans_dest_cs2_5251[MATRIX_ROWS_DEST][MATRIX_COLS_DEST] = {

  { UNIMAP_NO,  UNIMAP_Z,    UNIMAP_X,    UNIMAP_C,    UNIMAP_V,  UNIMAP_B,    UNIMAP_N,    UNIMAP_M   }, // 00-07
  { UNIMAP_COMMA,  UNIMAP_DOT,    UNIMAP_SLASH,    UNIMAP_NO,    UNIMAP_KP_SLASH,  UNIMAP_NO,    UNIMAP_NONUS_BSLASH,    UNIMAP_SPACE   }, // 08-0F
  { UNIMAP_NO,  UNIMAP_A,    UNIMAP_S,    UNIMAP_D,    UNIMAP_F,  UNIMAP_G,    UNIMAP_H,    UNIMAP_J   }, // 10-17
  { UNIMAP_K,  UNIMAP_L,    UNIMAP_SCOLON,    UNIMAP_QUOTE,    UNIMAP_BSLASH,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 18-1F
  { UNIMAP_TAB,  UNIMAP_Q,    UNIMAP_W,    UNIMAP_E,    UNIMAP_R,  UNIMAP_T,    UNIMAP_Y,    UNIMAP_U   }, // 20-27
  { UNIMAP_I,  UNIMAP_O,    UNIMAP_P,    UNIMAP_LBRACKET,    UNIMAP_RBRACKET,  UNIMAP_ENTER,    UNIMAP_NO,    UNIMAP_NO   }, // 28-2F
  { UNIMAP_NO,  UNIMAP_1,    UNIMAP_2,    UNIMAP_3,    UNIMAP_4,  UNIMAP_5,    UNIMAP_6,    UNIMAP_7   }, // 30-37
  { UNIMAP_8,  UNIMAP_9,    UNIMAP_0,    UNIMAP_MINS,    UNIMAP_EQL,  UNIMAP_BSPC,    UNIMAP_GRV,    UNIMAP_NO   }, // 38-3F
  { UNIMAP_KP_0,  UNIMAP_KP_1,    UNIMAP_KP_2,    UNIMAP_KP_3,    UNIMAP_KP_4,  UNIMAP_KP_5,    UNIMAP_KP_6,    UNIMAP_KP_7   }, // 40-47
  { UNIMAP_KP_8,  UNIMAP_KP_9,    UNIMAP_KP_DOT,    UNIMAP_NLCK,    UNIMAP_KP_MINUS,  UNIMAP_KP_ENTER,    UNIMAP_KP_PLUS,    UNIMAP_NO   }, // 48-4F
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_CAPSLOCK,  UNIMAP_NO,    UNIMAP_RSHIFT,    UNIMAP_LSHIFT   }, // 50-57
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 58-5F
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 60-67
  { UNIMAP_RCTRL,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_F3,  UNIMAP_F4,    UNIMAP_F5,    UNIMAP_F2   }, // 68-6F
  { UNIMAP_F8,  UNIMAP_F7,    UNIMAP_F9,    UNIMAP_F10,    UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 70-77
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_F1,  UNIMAP_F6,    UNIMAP_LCTRL,    UNIMAP_NO   }, // 78-7F
  //   0             1             2             3             4           5            6             7
  //   8             9             A             B             C           D            E             F
};


const uint8_t PROGMEM unimap_trans_dest_cs3_5251[MATRIX_ROWS_DEST][MATRIX_COLS_DEST] = {

  { UNIMAP_NO,  UNIMAP_Z,    UNIMAP_X,    UNIMAP_C,    UNIMAP_V,  UNIMAP_B,    UNIMAP_N,    UNIMAP_M   }, // 00-07
  { UNIMAP_COMMA,  UNIMAP_DOT,    UNIMAP_SLASH,    UNIMAP_NO,    UNIMAP_NUMLOCK,  UNIMAP_NO,    UNIMAP_NONUS_BSLASH,    UNIMAP_SPACE   }, // 08-0F
  { UNIMAP_NO,  UNIMAP_A,    UNIMAP_S,    UNIMAP_D,    UNIMAP_F,  UNIMAP_G,    UNIMAP_H,    UNIMAP_J   }, // 10-17
  { UNIMAP_K,  UNIMAP_L,    UNIMAP_SCOLON,    UNIMAP_QUOTE,    UNIMAP_BSLASH,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 18-1F
  { UNIMAP_TAB,  UNIMAP_Q,    UNIMAP_W,    UNIMAP_E,    UNIMAP_R,  UNIMAP_T,    UNIMAP_Y,    UNIMAP_U   }, // 20-27
  { UNIMAP_I,  UNIMAP_O,    UNIMAP_P,    UNIMAP_LBRACKET,    UNIMAP_RBRACKET,  UNIMAP_ENTER,    UNIMAP_NO,    UNIMAP_NO   }, // 28-2F
  { UNIMAP_NO,  UNIMAP_1,    UNIMAP_2,    UNIMAP_3,    UNIMAP_4,  UNIMAP_5,    UNIMAP_6,    UNIMAP_7   }, // 30-37
  { UNIMAP_8,  UNIMAP_9,    UNIMAP_0,    UNIMAP_MINS,    UNIMAP_EQL,  UNIMAP_BSPC,    UNIMAP_GRV,    UNIMAP_NO   }, // 38-3F
  { UNIMAP_KP_0,  UNIMAP_KP_1,    UNIMAP_KP_2,    UNIMAP_KP_3,    UNIMAP_KP_4,  UNIMAP_KP_5,    UNIMAP_KP_6,    UNIMAP_KP_7   }, // 40-47
  { UNIMAP_KP_8,  UNIMAP_KP_9,    UNIMAP_KP_DOT,    UNIMAP_ESCAPE,    UNIMAP_KP_ASTERISK,  UNIMAP_KP_ENTER,    UNIMAP_KP_PLUS,    UNIMAP_NO   }, // 48-4F
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_CAPSLOCK,  UNIMAP_NO,    UNIMAP_RSHIFT,    UNIMAP_LSHIFT   }, // 50-57
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 58-5F
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 60-67
  { UNIMAP_RCTRL,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    0xE9,  UNIMAP_PAUSE,    0xEA,    0x8A   }, // 68-6F
  { UNIMAP_APP,  UNIMAP_PSCR,    0xE3,    0xE7,    UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO   }, // 70-77
  { UNIMAP_NO,  UNIMAP_NO,    UNIMAP_NO,    UNIMAP_NO,    0xE2,  0x8B,    UNIMAP_LCTRL,    UNIMAP_NO   }, // 78-7F
  //   0             1             2             3             4           5            6             7
  //   8             9             A             B             C           D            E             F
};


const uint8_t PROGMEM unimap_trans_dest_cs3_5251_extra[MATRIX_ROWS_DEST][MATRIX_COLS_DEST] = {
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 00-07
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 08-0F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 10-17
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 18-1F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 20-27
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 28-2F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 30-37
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 38-3F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 40-47
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 48-4F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 50-57
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 58-5F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 60-67
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_F3,  UNIMAP_F4,  UNIMAP_F5,  UNIMAP_F2   }, // 68-6F
  { UNIMAP_F8,  UNIMAP_F7, UNIMAP_F9,  UNIMAP_F10, UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 70-77
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_F1,  UNIMAP_F6,  UNIMAP_NO,  UNIMAP_NO  }, // 78-7F
  //   0             1         2          3          4           5            6             7
  //   8             9         A          B          C           D            E             F
};





const uint8_t PROGMEM unimap_trans_dest_3278_alted[MATRIX_ROWS_DEST][MATRIX_COLS_DEST] = {

  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F10 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_F11,  UNIMAP_NO    }, // 00-07
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F8 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 08-0F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F4 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 10-17
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 18-1F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F2 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 20-27
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 28-2F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F6 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 30-37
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 38-3F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F1 , UNIMAP_NO , UNIMAP_F12,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 40-47
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F9 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 48-4F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F5 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_END,  UNIMAP_NO   }, // 50-57
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 58-5F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F3 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 60-67
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 68-6F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F7 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 70-77
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO  }, // 78-7F
  //   0             1         2          3          4           5            6             7
  //   8             9         A          B          C           D            E             F
};




const uint8_t PROGMEM unimap_trans_dest_cs1_3278[MATRIX_ROWS_DEST][MATRIX_COLS_DEST] = {
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_0 , UNIMAP_A , UNIMAP_SPACE,  UNIMAP_F3,  UNIMAP_MINS,  UNIMAP_Q    }, // 00-07
  { UNIMAP_ENTER,  UNIMAP_NO, UNIMAP_8, UNIMAP_I , UNIMAP_KP_DOT,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_Y    }, // 08-0F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_4 , UNIMAP_E , UNIMAP_SLASH,  UNIMAP_F7,  UNIMAP_LCTRL,  UNIMAP_U    }, // 10-17
  { UNIMAP_KP_9,  UNIMAP_NO, UNIMAP_NO , UNIMAP_M , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 18-1F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_2 , UNIMAP_C , UNIMAP_QUOTE,  UNIMAP_F5,  UNIMAP_DOT,  UNIMAP_S    }, // 20-27
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO, UNIMAP_K , UNIMAP_KP_3,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 28-2F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_6 , UNIMAP_G , UNIMAP_KP_1,  UNIMAP_F9,  UNIMAP_TAB,  UNIMAP_W    }, // 30-37
  { UNIMAP_KP_5,  UNIMAP_NO, UNIMAP_NO, UNIMAP_O , UNIMAP_NO,  UNIMAP_KP_8,  UNIMAP_NO,  UNIMAP_SCOLON   }, // 38-3F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_1 , UNIMAP_B , UNIMAP_EQL,  UNIMAP_F4,  UNIMAP_BSPC,  UNIMAP_R    }, // 40-47
  { UNIMAP_NONUS_BSLASH,  UNIMAP_NO, UNIMAP_9, UNIMAP_J , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_Z    }, // 48-4F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_5 , UNIMAP_F , UNIMAP_RBRACKET,  UNIMAP_F8,  UNIMAP_KP_0,  UNIMAP_V    }, // 50-57
  { UNIMAP_KP_4,  UNIMAP_NO, UNIMAP_NO, UNIMAP_N , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_ESCAPE,  UNIMAP_NO   }, // 58-5F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_3 , UNIMAP_D , UNIMAP_KP_2,  UNIMAP_F6,  UNIMAP_COMMA,  UNIMAP_T    }, // 60-67
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO, UNIMAP_L , UNIMAP_LBRACKET,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 68-6F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_7 , UNIMAP_H , UNIMAP_NO,  UNIMAP_F10,  UNIMAP_NO,  UNIMAP_X    }, // 70-77
  { UNIMAP_BSLASH,  UNIMAP_NO, UNIMAP_NO, UNIMAP_P , UNIMAP_NO,  UNIMAP_KP_7,  UNIMAP_NO,  UNIMAP_NO   }, // 78-7F
  //   0             1         2          3          4           5            6             7
  //   8             9         A          B          C           D            E             F
};


const uint8_t PROGMEM unimap_trans_dest_cs2_3278[MATRIX_ROWS_DEST][MATRIX_COLS_DEST] = {
  { UNIMAP_NO,  UNIMAP_F13, UNIMAP_0 , UNIMAP_A , UNIMAP_SPACE,  UNIMAP_KP_9,  UNIMAP_MINS,  UNIMAP_Q    }, // 00-07
  { UNIMAP_ENTER,  UNIMAP_F21, UNIMAP_8, UNIMAP_I , UNIMAP_RCTRL,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_Y    }, // 08-0F
  { UNIMAP_NO,  UNIMAP_F17, UNIMAP_4 , UNIMAP_E , UNIMAP_SLASH,  UNIMAP_KP_6,  UNIMAP_LCTRL,  UNIMAP_U    }, // 10-17
  { UNIMAP_PGUP,  UNIMAP_NO, UNIMAP_NO , UNIMAP_M , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 18-1F
  { UNIMAP_NO,  UNIMAP_F15, UNIMAP_2 , UNIMAP_C , UNIMAP_QUOTE,  UNIMAP_KP_2,  UNIMAP_DOT,  UNIMAP_S    }, // 20-27
  { UNIMAP_NO,  UNIMAP_F23, UNIMAP_NO, UNIMAP_K , UNIMAP_RIGHT,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 28-2F
  { UNIMAP_NO,  UNIMAP_F19, UNIMAP_6 , UNIMAP_G , UNIMAP_LEFT,  UNIMAP_KP_4,  UNIMAP_TAB,  UNIMAP_W    }, // 30-37
  { UNIMAP_UP,  UNIMAP_NO, UNIMAP_NO, UNIMAP_O , UNIMAP_NO,  UNIMAP_HOME,  UNIMAP_NO,  UNIMAP_SCOLON   }, // 38-3F
  { UNIMAP_NO,  UNIMAP_F14, UNIMAP_1 , UNIMAP_B , UNIMAP_EQL,  UNIMAP_KP_8,  UNIMAP_BSPC,  UNIMAP_R    }, // 40-47
  { UNIMAP_NONUS_BSLASH,  UNIMAP_F22, UNIMAP_9, UNIMAP_J , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_Z    }, // 48-4F
  { UNIMAP_NO,  UNIMAP_F18, UNIMAP_5 , UNIMAP_F , UNIMAP_RBRACKET,  UNIMAP_KP_5,  UNIMAP_KP_0,  UNIMAP_V    }, // 50-57
  { UNIMAP_DELETE,  UNIMAP_NO, UNIMAP_NO, UNIMAP_N , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_GRAVE,  UNIMAP_NO   }, // 58-5F
  { UNIMAP_NO,  UNIMAP_F16, UNIMAP_3 , UNIMAP_D , UNIMAP_DOWN,  UNIMAP_KP_7,  UNIMAP_COMMA,  UNIMAP_T    }, // 60-67
  { UNIMAP_NO,  UNIMAP_F24, UNIMAP_NO, UNIMAP_L , UNIMAP_LBRACKET,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 68-6F
  { UNIMAP_NO,  UNIMAP_F20, UNIMAP_7 , UNIMAP_H , UNIMAP_NO,  UNIMAP_KP_3,  UNIMAP_NO,  UNIMAP_X    }, // 70-77
  { UNIMAP_BSLASH,  UNIMAP_NO, UNIMAP_NO, UNIMAP_P , UNIMAP_NO,  UNIMAP_INSERT,  UNIMAP_NO,  UNIMAP_NO   }, // 78-7F
  //   0             1         2          3          4           5            6             7
  //   8             9         A          B          C           D            E             F
};

const uint8_t PROGMEM unimap_trans_dest_cs3_3278[MATRIX_ROWS_DEST][MATRIX_COLS_DEST] = {
    { UNIMAP_NO,  UNIMAP_F13, UNIMAP_0 , UNIMAP_A , UNIMAP_SPACE,  UNIMAP_KP_9,  UNIMAP_MINS,  UNIMAP_Q    }, // 00-07
    { UNIMAP_ENTER,  UNIMAP_F21, UNIMAP_8, UNIMAP_I , UNIMAP_RCTRL,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_Y    }, // 08-0F
    { UNIMAP_NO,  UNIMAP_F17, UNIMAP_4 , UNIMAP_E , UNIMAP_SLASH,  UNIMAP_KP_6,  UNIMAP_LCTRL,  UNIMAP_U    }, // 10-17
    { UNIMAP_PGDOWN,  UNIMAP_NO, UNIMAP_NO , UNIMAP_M , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 18-1F
    { UNIMAP_NO,  UNIMAP_F15, UNIMAP_2 , UNIMAP_C , UNIMAP_QUOTE,  UNIMAP_KP_2,  UNIMAP_DOT,  UNIMAP_S    }, // 20-27
    { UNIMAP_NO,  UNIMAP_F23, UNIMAP_NO, UNIMAP_K , UNIMAP_RIGHT,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 28-2F
    { UNIMAP_NO,  UNIMAP_F19, UNIMAP_6 , UNIMAP_G , UNIMAP_LEFT,  UNIMAP_KP_4,  UNIMAP_TAB,  UNIMAP_W    }, // 30-37
    { UNIMAP_UP,  UNIMAP_NO, UNIMAP_NO, UNIMAP_O , UNIMAP_NO,  UNIMAP_PGUP,  UNIMAP_NO,  UNIMAP_SCOLON   }, // 38-3F
    { UNIMAP_NO,  UNIMAP_F14, UNIMAP_1 , UNIMAP_B , UNIMAP_EQL,  UNIMAP_KP_8,  UNIMAP_BSPC,  UNIMAP_R    }, // 40-47
    { UNIMAP_NONUS_BSLASH,  UNIMAP_F22, UNIMAP_9, UNIMAP_J , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_Z    }, // 48-4F
    { UNIMAP_NO,  UNIMAP_F18, UNIMAP_5 , UNIMAP_F , UNIMAP_RBRACKET,  UNIMAP_KP_5,  UNIMAP_KP_0,  UNIMAP_V    }, // 50-57
    { UNIMAP_END,  UNIMAP_NO, UNIMAP_NO, UNIMAP_N , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_GRAVE,  UNIMAP_NO   }, // 58-5F
    { UNIMAP_NO,  UNIMAP_F16, UNIMAP_3 , UNIMAP_D , UNIMAP_DOWN,  UNIMAP_KP_7,  UNIMAP_COMMA,  UNIMAP_T    }, // 60-67
    { UNIMAP_NO,  UNIMAP_F24, UNIMAP_NO, UNIMAP_L , UNIMAP_LBRACKET,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 68-6F
    { UNIMAP_NO,  UNIMAP_F20, UNIMAP_7 , UNIMAP_H , UNIMAP_NO,  UNIMAP_KP_3,  UNIMAP_NO,  UNIMAP_X    }, // 70-77
    { UNIMAP_NONUS_HASH,  UNIMAP_NO, UNIMAP_NO, UNIMAP_P , UNIMAP_NO,  UNIMAP_KP_SLASH,  UNIMAP_NO,  UNIMAP_NO   }, // 78-7F
    //   0             1         2          3          4           5            6             7
    //   8             9         A          B          C           D            E             F
};



const uint8_t PROGMEM unimap_trans_dest_cs3_3278_extra[MATRIX_ROWS_DEST][MATRIX_COLS_DEST] = {
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  0xE9,  UNIMAP_NO,  UNIMAP_NO    }, // 00-07
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 08-0F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  0x46,  UNIMAP_NO,  UNIMAP_NO    }, // 10-17
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 18-1F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  0xEA,  UNIMAP_NO,  UNIMAP_NO   }, // 20-27
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 28-2F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  0xE3,  UNIMAP_NO,  UNIMAP_NO    }, // 30-37
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 38-3F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  0x48,  UNIMAP_NO,  UNIMAP_NO    }, // 40-47
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 48-4F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  0x65,  UNIMAP_NO,  UNIMAP_NO   }, // 50-57
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 58-5F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  0x8B,  UNIMAP_NO,  UNIMAP_NO    }, // 60-67
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 68-6F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  0xE7,  UNIMAP_NO,  UNIMAP_NO   }, // 70-77
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO  }, // 78-7F
  //   0             1         2          3          4           5            6             7
  //   8             9         A          B          C           D            E             F
};


const uint8_t PROGMEM unimap_trans_dest_cs3_3278_alted[MATRIX_ROWS_DEST][MATRIX_COLS_DEST] = {

  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F10 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_F11,  UNIMAP_NO    }, // 00-07
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F8 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 08-0F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F4 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 10-17
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 18-1F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F2 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 20-27
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 28-2F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F6 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 30-37
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 38-3F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F1 , UNIMAP_NO , UNIMAP_F12,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 40-47
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F9 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 48-4F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F5 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_INSERT,  UNIMAP_NO   }, // 50-57
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 58-5F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F3 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO    }, // 60-67
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 68-6F
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_F7 , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO   }, // 70-77
  { UNIMAP_NO,  UNIMAP_NO, UNIMAP_NO , UNIMAP_NO , UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO,  UNIMAP_NO  }, // 78-7F
  //   0             1         2          3          4           5            6             7
  //   8             9         A          B          C           D            E             F
};
