# TMK Converter rev.1
# which looks like this:
# https://github.com/tmk/keyboard_converter#pcb-rev1
TARGET = ps2_ibm4704_rev1
MCU = atmega32u4

BOOTMAGIC_ENABLE ?= no
MOUSEKEY_ENABLE ?= no
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= yes
COMMAND_ENABLE ?= yes
NKRO_ENABLE ?= yes

PS2_USE_USART = no
PS2_USE_INT = yes
PS2_USE_BUSYWAIT = no

UNIMAP_ENABLE = yes
KEYMAP_SECTION_ENABLE = yes

include Makefile
